version: '3.3'

services:
  app:
    build: .
#    depends_on:
#      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=mydatabaseuser
#      - POSTGRES_PASSWORD=mypassword


#  db:
#    image: postgres
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=mydatabaseuser
#      - POSTGRES_PASSWORD=mypassword
#    expose:
#      - 5432
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
