# Generated by Django 4.2.5 on 2023-09-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id']},
        ),
    ]
